name: Compile FEX (Linux ARM64)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile-fex-linux:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y clang lld cmake ninja-build python3 \
            libgl1-mesa-dev libvulkan-dev libx11-dev zlib1g-dev

      - name: Compile FEX (Linux ARM64)
        run: |
          mkdir -p build/linux && cd build/linux
          cmake ../../ -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS_RELEASE="-O3 -march=armv8-a+simd -mtune=cortex-a76" \
            -DCMAKE_CXX_FLAGS_RELEASE="-O3 -march=armv8-a+simd -mtune=cortex-a76"
          ninja

      - name: Package FEX binaries
        run: |
          mkdir FEX_Linux_Build
          cp -v ./build/linux/Bin/FEX* ./FEX_Linux_Build/ || true
          cp -v ./build/linux/Bin/lib*.so ./FEX_Linux_Build/ || true
          mkdir -p ./FEX_Linux_Package/usr/bin ./FEX_Linux_Package/usr/lib
          cp -v ./build/linux/Bin/FEX* ./FEX_Linux_Package/usr/bin/ || true
          cp -v ./build/linux/Bin/lib*.so ./FEX_Linux_Package/usr/lib/ || true
          cd FEX_Linux_Package
          TODAY=$(date +'%y%m%d')
          tar --zstd -cf ../FEX-Linux-ARM64-${TODAY}.tar.zst usr
          cd ..

      - name: Upload FEX Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: FEX Linux ARM64 Binaries
          path: |
            ./FEX_Linux_Build/
            ./FEX-Linux-ARM64-*.tar.zst

      - name: "Set Date Variable"
        id: date
        run: echo "date=$(date +'%y%m%d')" >> $GITHUB_ENV

      - name: "Create Release"
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          name: "FEX-Linux-ARM64-${{ env.date }}"
          tag_name: "${{ env.date }}"
          prerelease: false
          文件: |
            ./FEX_Linux_Build/**
            ./FEX-Linux-ARM64-*.tar.zst
