name: Compile FEXCore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile-fexcore:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
         
      - name: Install Nix Package Manager
        uses: cachix/install-nix-action@v31
        with:
         nix_path: nixpkgs=channel:nixos-unstable
        
      - name: Compile FEXCore
        run: |
          mkdir -p build/arm64ec && cd build/arm64ec
          ../../Data/nix/cmake_configure_woa64.sh ../../ -G Ninja
          ninja
          mkdir ../wow64 && cd ../wow64
          ../../Data/nix/cmake_configure_woa32.sh ../../ -G Ninja
          ninja

      - name: Package FEXCore DLLs
        run: |
          mkdir FEXCore_DLLs
          cp -r ./build/arm64ec/Bin/libarm64ecfex.dll ./FEXCore_DLLs
          cp -r ./build/wow64/Bin/libwow64fex.dll ./FEXCore_DLLs


      - name: Upload FEXCore_DLLs
        uses: actions/upload-artifact@v4
        with:
         name: FEXCore DLLs
         path: ./FEXCore_DLLs
